[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
exclude = [
      './server/pages/500.html',
      './server/pages/404.html',
      '/server/pages/500.html',
      '/server/pages/404.html'
  ]