[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "public"
  filePath = "/pages/sitemap.xml"
  exclude = [
    './build-dir/path-to/_document.js',
    './build-dir/path-to/_app.js',
  ]